
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "QSnake", email = "jester36883688@gmail.com"},
]
dependencies = [
    "pandas>=2.1.3",
    "pyarrow>=14.0.1",
    "fastparquet>=2023.10.1",
]
requires-python = ">=3.10"
license = {text = "MIT"}
